name: Pytest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        poetry install
    - name: Pytest
      run: |
        poetry run pytest -v
        pwd
        ls -a
        cd logs
        ls -a
        cd pytest
        ls -a
    - name: Upload coverage to Codecov
      run: |
        pwd
        ls -a
        cd logs
        ls -a
        cd pytest
        ls -a    
      uses: codecov/codecov-action@master
      with:
        files: pytest-coverage
        directory: logs/pytest/
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
      run: |
        pwd
        ls -a
        cd logs
        ls -a
        cd pytest
        ls -a



